
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - ZIPKIN_HTTP_PORT=9411
    networks:
      - zipkin-network

networks:
  zipkin-network:
    driver: bridge
