swagger: "2.0"
info:
  title: "RabbitMQ_spring API"
  description: "RabbitMQ_spring API"
  version: "1.0.0"
host: mancityfake.online:8085
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /orders:
    post:
      summary: "POST api/orders"
      operationId: "createOrder"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
      x-google-backend:
        address: http://mancityfake.online:8085
        protocol: "http/1.1"
